backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "/" # Media files will be stored in the repo under images/uploads
public_folder: "/"
collections:
  - name: "Upload files"
    label: "Upload files"
    files:
    - label: "Upload files"
      name: "Upload files"
      file: "cdn.json"
      fields:
        - { label: "Title", name: "title", widget: "string"}
  